// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: authentication/v1/service.proto

package authenticationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	login "moufube.com/m/internal/generated/pb/authentication/v1/login"
	register "moufube.com/m/internal/generated/pb/authentication/v1/register"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_authentication_v1_service_proto protoreflect.FileDescriptor

const file_authentication_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1fauthentication/v1/service.proto\x12\x11authentication.v1\x1a(authentication/v1/register/request.proto\x1a)authentication/v1/register/response.proto\x1a%authentication/v1/login/request.proto\x1a&authentication/v1/login/response.proto2\xb9\x01\n" +
	"\x0eAuthentication\x12W\n" +
	"\bRegister\x12#.authentication.v1.register.Request\x1a$.authentication.v1.register.Response\"\x00\x12N\n" +
	"\x05Login\x12 .authentication.v1.login.Request\x1a!.authentication.v1.login.Response\"\x00B?Z=moufube.com/m/generated/pb/authentication/v1;authenticationpbb\x06proto3"

var file_authentication_v1_service_proto_goTypes = []any{
	(*register.Request)(nil),  // 0: authentication.v1.register.Request
	(*login.Request)(nil),     // 1: authentication.v1.login.Request
	(*register.Response)(nil), // 2: authentication.v1.register.Response
	(*login.Response)(nil),    // 3: authentication.v1.login.Response
}
var file_authentication_v1_service_proto_depIdxs = []int32{
	0, // 0: authentication.v1.Authentication.Register:input_type -> authentication.v1.register.Request
	1, // 1: authentication.v1.Authentication.Login:input_type -> authentication.v1.login.Request
	2, // 2: authentication.v1.Authentication.Register:output_type -> authentication.v1.register.Response
	3, // 3: authentication.v1.Authentication.Login:output_type -> authentication.v1.login.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_v1_service_proto_init() }
func file_authentication_v1_service_proto_init() {
	if File_authentication_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_v1_service_proto_rawDesc), len(file_authentication_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authentication_v1_service_proto_goTypes,
		DependencyIndexes: file_authentication_v1_service_proto_depIdxs,
	}.Build()
	File_authentication_v1_service_proto = out.File
	file_authentication_v1_service_proto_goTypes = nil
	file_authentication_v1_service_proto_depIdxs = nil
}
