// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: authentication/dto/response/register_response.proto

package response

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_authentication_dto_response_register_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_dto_response_register_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_authentication_dto_response_register_response_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

var File_authentication_dto_response_register_response_proto protoreflect.FileDescriptor

const file_authentication_dto_response_register_response_proto_rawDesc = "" +
	"\n" +
	"3authentication/dto/response/register_response.proto\x12\x1bauthentication.dto.response\"]\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHashB9Z7github.com/moufube.com/m/pb/authentication/dto/responseb\x06proto3"

var (
	file_authentication_dto_response_register_response_proto_rawDescOnce sync.Once
	file_authentication_dto_response_register_response_proto_rawDescData []byte
)

func file_authentication_dto_response_register_response_proto_rawDescGZIP() []byte {
	file_authentication_dto_response_register_response_proto_rawDescOnce.Do(func() {
		file_authentication_dto_response_register_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_dto_response_register_response_proto_rawDesc), len(file_authentication_dto_response_register_response_proto_rawDesc)))
	})
	return file_authentication_dto_response_register_response_proto_rawDescData
}

var file_authentication_dto_response_register_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authentication_dto_response_register_response_proto_goTypes = []any{
	(*RegisterResponse)(nil), // 0: authentication.dto.response.RegisterResponse
}
var file_authentication_dto_response_register_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_dto_response_register_response_proto_init() }
func file_authentication_dto_response_register_response_proto_init() {
	if File_authentication_dto_response_register_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_dto_response_register_response_proto_rawDesc), len(file_authentication_dto_response_register_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_dto_response_register_response_proto_goTypes,
		DependencyIndexes: file_authentication_dto_response_register_response_proto_depIdxs,
		MessageInfos:      file_authentication_dto_response_register_response_proto_msgTypes,
	}.Build()
	File_authentication_dto_response_register_response_proto = out.File
	file_authentication_dto_response_register_response_proto_goTypes = nil
	file_authentication_dto_response_register_response_proto_depIdxs = nil
}
