// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: authentication/usecase/authentication.proto

package usecase

import (
	request "github.com/moufube.com/m/pb/authentication/dto/request"
	response "github.com/moufube.com/m/pb/authentication/dto/response"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_authentication_usecase_authentication_proto protoreflect.FileDescriptor

const file_authentication_usecase_authentication_proto_rawDesc = "" +
	"\n" +
	"+authentication/usecase/authentication.proto\x12\x16authentication.usecase\x1a1authentication/dto/request/register_request.proto\x1a3authentication/dto/response/register_response.proto2z\n" +
	"\x0eAuthentication\x12h\n" +
	"\bRegister\x12+.authentication.dto.request.RegisterRequest\x1a-.authentication.dto.response.RegisterResponse\"\x00B%Z#github.com/moufube.com/m/pb/usecaseb\x06proto3"

var file_authentication_usecase_authentication_proto_goTypes = []any{
	(*request.RegisterRequest)(nil),   // 0: authentication.dto.request.RegisterRequest
	(*response.RegisterResponse)(nil), // 1: authentication.dto.response.RegisterResponse
}
var file_authentication_usecase_authentication_proto_depIdxs = []int32{
	0, // 0: authentication.usecase.Authentication.Register:input_type -> authentication.dto.request.RegisterRequest
	1, // 1: authentication.usecase.Authentication.Register:output_type -> authentication.dto.response.RegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_usecase_authentication_proto_init() }
func file_authentication_usecase_authentication_proto_init() {
	if File_authentication_usecase_authentication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_usecase_authentication_proto_rawDesc), len(file_authentication_usecase_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authentication_usecase_authentication_proto_goTypes,
		DependencyIndexes: file_authentication_usecase_authentication_proto_depIdxs,
	}.Build()
	File_authentication_usecase_authentication_proto = out.File
	file_authentication_usecase_authentication_proto_goTypes = nil
	file_authentication_usecase_authentication_proto_depIdxs = nil
}
